{{- if and .Values.storage.db.enabled .Values.storage.db.selfHosted }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: {{ .Values.storage.db.replicas | default 1 }}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.storage.db.image.name }}:{{ .Values.storage.db.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: PGDATA
          value: /var/lib/postgresql/mlflow/data
        envFrom:
        - secretRef:
            name: postgres-env
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/mlflow
  volumeClaimTemplates:
  - metadata:
      name: postgres-pvc
    spec:
      accessModes:
      - {{ .Values.storage.db.volume.accessMode }}
      resources:
        requests:
          storage: {{ .Values.storage.db.volume.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres

{{- end }}